# config/tasks.yaml

research_task:
  description: >-
    Conduct ideation for innovative family games and competitions.
    Focus on activities that foster learning and growth, and are
    suitable for a family of five (Father, Mother, two Sons aged
    26 and 16, and two Daughters aged 24 and 17). Generate a diverse
    set of game ideas, each self-contained and easy to understand.
  expected_output: >-
    A list of {num_bullet_points} unique game-idea strings.
  agent: researcher

reporting_task:
  description: >-
    Take the research output and refine each game idea for my family:
    Father, Mother, two Sons (26, 16), and two Daughters (24, 17).
    For each idea, provide:
      - Gameplay instructions
      - Required materials
      - Setup steps
      - Scoring rules
      - Additional tips for maximum fun
    Ensure every activity includes a competitive element.
  expected_output: >-
    A list of {num_bullet_points} detailed, refined game-idea strings
    formatted in Markdown (no ``` fences).
  agent: reporting_analyst
  markdown: true
  output_file: family_games_report.md
